#****************************************************************************
# Copyright (C) 2018 pmdtechnologies ag & Infineon Technologies
#
# THIS CODE AND INFORMATION ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY
# KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A
# PARTICULAR PURPOSE.
#
#****************************************************************************

set(OpenNI2_FOUND 0)

if(CMAKE_SIZEOF_VOID_P EQUAL 4)
    # Regular x86
    set(TMP_PROG_PATH $ENV{PROGRAMW6432})
    set(TMP_OPENNI_ENV_LIB $ENV{OPENNI2_LIB})
    set(TMP_OPENNI_ENV_INC $ENV{OPENNI2_INCLUDE})
else()
    # x64
    set(TMP_PROG_PATH $ENV{PROGRAMFILES})
    set(TMP_OPENNI_ENV_LIB $ENV{OPENNI2_LIB64})
    set(TMP_OPENNI_ENV_INC $ENV{OPENNI2_INCLUDE64})
endif()

set(OPENNI2_DEFINITIONS ${PC_OPENNI_CFLAGS_OTHER})
FIND_LIBRARY( OPENNI2_LIBRARY
             NAMES OpenNI2
             HINTS ${PC_OPENNI2_LIBDIR} ${PC_OPENNI2_LIBRARY_DIRS} /usr/lib
             PATHS "${TMP_PROG_PATH}/OpenNI2/Lib${OPENNI2_SUFFIX}" "$ENV{PROGRAMW6432}/OpenNI2" "${TMP_OPENNI_ENV_LIB}"
             PATH_SUFFIXES lib lib64
)
FIND_PATH( OPENNI2_INCLUDE_DIR OpenNI.h
          HINTS ${PC_OPENNI2_INCLUDEDIR} ${PC_OPENNI2_INCLUDE_DIRS} 
                  /usr/include/openni2 /usr/include/ni2
                  PATHS "${TMP_PROG_PATH}/OpenNI2/include" "${TMP_OPENNI_ENV_INC}"
          PATH_SUFFIXES openni2 ni2)

if (OPENNI2_INCLUDE_DIR)
    FILE(READ "${OPENNI2_INCLUDE_DIR}/OniVersion.h" OpenNIVersionHeader)

    STRING(REGEX MATCH "^.*\#define ONI_VERSION_MAJOR[^0-9]+([0-9]+).*$" _TMP_VERSION_IN ${OpenNIVersionHeader})
    SET(OPENNI_VERSION_MAJOR ${CMAKE_MATCH_1})
    STRING(REGEX MATCH "^.*\#define ONI_VERSION_MINOR[^0-9]+([0-9]+).*$" _TMP_VERSION_IN ${OpenNIVersionHeader})
    SET(OPENNI_VERSION_MINOR ${CMAKE_MATCH_1})
    STRING(REGEX MATCH "^.*\#define ONI_VERSION_MAINTENANCE[^0-9]+([0-9]+).*$" _TMP_VERSION_IN ${OpenNIVersionHeader})
    SET(OPENNI_VERSION_MAINTENANCE ${CMAKE_MATCH_1})
    STRING(REGEX MATCH "^.*\#define ONI_VERSION_BUILD[^0-9]+([0-9]+).*$" _TMP_VERSION_IN ${OpenNIVersionHeader})
    SET(OPENNI_VERSION_BUILD ${CMAKE_MATCH_1})
    SET(OPENNI_VERSION "${OPENNI_VERSION_MAJOR}.${OPENNI_VERSION_MINOR}.${OPENNI_VERSION_MAINTENANCE}.${OPENNI_VERSION_BUILD}")
endif ()

include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(OpenNI2
   FOUND_VAR OpenNI2_FOUND
   REQUIRED_VARS OPENNI2_LIBRARY OPENNI2_INCLUDE_DIR
   VERSION_VAR OPENNI_VERSION
   )
